### ISSUE TITLE
get_climatologies

### ISSUE THREAD

**Issue by BenMGeo** [pygeo/geoval#4]
I think it would be more practicable if the get_climatologies() method would return a GeoData object, so it could be handled the same way as the original data set.

**Comment by bulli92** [comment]
Hi,

in principle this is possible for many GeoVal functions already.
Normally the argument is called "return_object" or sometimes also 
"return_data"
I dont have in mind of this is available for get_climatologies() already.

Best, Alex

Am 02.02.2017 um 10:32 schrieb BenMGeo:

**Comment by BenMGeo** [comment]
Found it, thanks.
